config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  post '/', to: 'users#login'
  post '/user/logout', to: 'users#logout'
  resources :users

  resources :posts do
    resources :comments
  end

  resources :categories, only: [:show, :new, :create]

  resources :votes, only: [:create, :destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  has_many :votes, as: :voteable
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes, as: :voteable
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :contents, presence: true
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_secure_password validations: false
  validates :username, presence: true
  validates :password, presence: true
  validates :email, presence: true
  validates :username, uniqueness: true
end

app/models/vote.rb
class Vote < ActiveRecord::Base
belongs_to :voteable, polymorphic: true
belongs_to :user
validates_uniqueness_of :user, scope: :voteable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :restricted, :logged_out_only, :editable, :check_if_starred, :nicetime
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def restricted
    if !logged_in?
      redirect_to root_path
    end
  end

  def logged_out_only
    if logged_in?
      redirect_to posts_path
    end
  end

  def editable(post)
    post.user_id == session[:user_id] || session[:user_id] == 3 #admins user id
  end

  def set_all_categories_for_navbar
    @categories = Category.all
  end
  def check_if_starred(voted_object)
    exists = Vote.where(user_id: session[:user_id]).find_each
    if !exists.nil?
      exists.each do |star|
        return true if star.voteable_id == voted_object.id
      end
    end
  end

  def nicetime(timestring)
    timestring.strftime("%D at %r")
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_all_categories_for_navbar
  def show
    @category = Category.find(params[:id])
    @comment = Comment.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))
    
    if @category.save
      flash[:notice] = "Category created successfully"
      redirect_to posts_path
    else
      render :new
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user_id = session[:user_id]
    if @comment.save
      flash[:success] = "Comment Posted Successfully"
      redirect_to posts_path(postcomments: "#{@comment.post.id}", anchor: "#{@comment.post.title}")
    else
        flash[:error] = "Comment cannot be Blank"
        redirect_to posts_path
    end
  end

  def edit

  end

  def update

  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :restricted
  before_action :set_all_categories_for_navbar, only: [:index,:new,:edit,:create,:update]
  before_action :set_post_var, only: [:edit, :update]
  def index 
    @posts = Post.all
    @comment = Comment.new
    @categories = Category.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]
    if @post.save
      flash[:success] = "Post created!"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Updated Successfully"
      redirect_to posts_path(anchor: @post.title)
    else
      render :edit
    end
  end

  private
  def post_params
    params.require(:post).permit(:title,:contents,:user_id, category_ids: [])
  end

  def set_post_var
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :restricted, except: [:create,:login,:new]
  before_action :set_all_categories_for_navbar, only: :show
  
  def index
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def login
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash[:error] = "Invalid Username/Password"
      redirect_to root_path(which_form: 'login')
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Registered Successfully"
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      render '/welcome/index'
    end
  end

  def show
    @user = User.find(params[:id])
    @comment = Comment.new
  end


  private
  def user_params
    params.require(:user).permit!
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = Vote.new
    @vote.user_id = current_user.id
    @vote.voteable_type = params[:type]
    @vote.voteable_id = params[:post]
    if @vote.save
    else
      @togo = Vote.find_by(user_id: current_user.id, voteable_id: params[:post])
      Vote.destroy(@togo.id)
    end
      respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  def destroy

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :logged_out_only
  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/categories/_category.html.erb
<p style="display:inline;"><span class="lead"><%= category.name %> | </span></p>

app/views/categories/new.html.erb
<%= render '/layouts/title', title: "New Category" %>
<%= render '/layouts/errors', error: @category %>
<div class='well'>
  <%= form_for @category do |f| %>
    <div class='form group'>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div><br>
    <%= f.submit "Create Category", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% all_posts = link_to('All Posts', posts_path) %>
<%= render 'layouts/title', title: "#{all_posts} &raquo; #{@category.name}".html_safe %>

<%= render '/posts/posts', posts: @category.posts %>

app/views/layouts/_errors.html.erb
<% if error.errors.any? %>
  <div class='alert alert-warning' role='alert'>
    <h5>There were some errors:</h5>
    <ul>
      <% error.errors.full_messages.each do |msg| %>
      <li><%=msg%></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_login.html.erb
<h1>Log in:</h1> 
<%= form_tag '/' do %>
  <div class="control-group">
    <%= label_tag :username %> 
    <%= text_field_tag(:username,"username",{class: "control-input"})%>
  </div>
  <div class="control-group">
    <%= label_tag :password %> 
    <%= password_field_tag(:password,"password",{class: "control-input"})%>
  </div>
  <%= submit_tag "Log In", class: "btn btn-lg btn-primary" %>
<% end %>
<%= link_to "Back", :back %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Post It", posts_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li>
        <%= link_to "New Post", new_post_path %>
      </li>

      <li class="dropdown">
        <%= link_to '#', class: 'dropdown-toggle', 'data-toggle'=>'dropdown' do %>
          <%= "#{User.find(session[:user_id]).username}" %> <span class='caret'></span>
        <% end %>
        <ul class="dropdown-menu">
          <li>
            <%= link_to user_path(current_user.id) do %>
            <i class='glyphicon glyphicon-user'></i> View Profile
            <% end %>
          </li> 
          <li>
            <%= link_to "Logout", user_logout_path, method: 'post' %>
          </li>
        </ul>
      </li>
      <li class="dropdown">
        <%= link_to '#', class: 'dropdown-toggle', 'data-toggle'=>'dropdown' do %>
          Categories <span class='caret'></span>
        <% end %>
        <ul class="dropdown-menu">  
          <% @categories.each do |category| %>
            <li><%= link_to category.name, category_path(category) %></li>
          <%end%>
          <hr>
          <li>
            <%= link_to(new_category_path) do %>
              <i class='glyphicon glyphicon-plus'></i> New Category 
            <%end%>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_sign_up.html.erb
<h1>Create Account</h1>
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "control-input" %>
  </div>
  <div class="control-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "control-input" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "control-input" %>
  </div>
  <%= f.submit "Create", class: "btn btn-lg btn-warning" %>
<% end %>

<%= link_to "Back", :back %>

app/views/layouts/_title.html.erb
<p class="lead"><%= title %></p><hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Post-it</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if logged_in? %>
  <%= render '/layouts/navigation' %>
<% end %>
<% if logged_in? %>
  <div class="container">
<% end %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
<%= yield %>
<% if logged_in? %>
  </div>
<% end %>
</body>
</html>

app/views/posts/_comments.html.erb
<div class='well'>
  <% post.comments.each do |comment| %>
    <p>
      <span style='font-weight:bold;'><%=comment.user.username %>: </span> <%=comment.body %> <span style="font-size:70%;">at <%=nicetime(comment.created_at) %></span> <% if params[:tab] == 'comments'%> On: <span style='font-weight:bold;'><%= comment.post.title %> </span><% end %>
    </p>
  <% end %>
  <%if params[:tab] != 'comments' %><%= link_to "Hide Comments", posts_path %><% end %>
</div>

app/views/posts/_form.html.erb
<div class="well form">
    <%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title%>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contents %>
    <%= f.text_area :contents, class: "form-control" %>
  </div>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox inline") + cb.text } %>
  <% end %>
  <%= f.submit "Create Post", class: "btn btn-primary" %>
<%end%>
</div>

app/views/posts/_new_comment.html.erb
<div class="well">
  <%= form_for [post, @comment] do |f| %>
    <div class='form-group'>
      <%= f.text_area :body, class: 'form-control' %>
    </div>
    <%= f.submit "Comment", class: 'btn btn-info' %>
  <% end %>
</div>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
<div class="well">
  <h3><%= render '/posts/stars', voted_object: post %></h3>
  <h3 class='quiet'>Posted In: <%= render post.categories %> </h3>
  <h1><a name="<%=post.title%>" style='text-decoration:none;'><%=post.title %></a>  <small><span style='font-weight:bold;'> By: </span><%=post.user.username%></small</h1>
  <br>
  <div class="well">
    <p><%=post.contents%></p>
  </div>
  <p><span style='font-weight:bold;'>Created on: </span><%=nicetime(post.created_at)%></p>
    <hr>
  <% if editable(post) %>
    <%= link_to "Edit Post", edit_post_path(post) %>
  <% end %>
  <hr>
  <p><span style='font-weight:bold;'>New Comment? </span></p>
  <%= render '/posts/new_comment', post: post %>
  <% if params[:postcomments] != "#{post.id}" %>
  <%= link_to "View all Comments (#{post.comments.size})", posts_path(postcomments: "#{post.id}", anchor: post.title) %>
  <% elsif params[:postcomments] == "#{post.id}" %>
  <%= render 'comments', post: post %>
  <% end %>
</div>
  <% end %>

app/views/posts/_stars.html.erb
<div class='starbox' id="star_<%=voted_object.id%>" style="float:right;">
<p><%= link_to votes_path(vote: 'true', post: voted_object, type: 'Post'), method: 'post', remote: true do %>
  <% if check_if_starred(voted_object)%>
    <i class='glyphicon glyphicon-certificate' style='color:yellow'></i>
  <% else %>
    <i class='glyphicon glyphicon-certificate'></i>
  <% end %>
  <% end %><span><%= voted_object.votes.size %></span> Stars</p>
</div>

app/views/posts/edit.html.erb
<%= render '/layouts/errors', error: @post %>
<%= render '/layouts/title', title: "Edit Post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render '/layouts/title', title: "All Posts" %>

<%= render '/posts/posts', posts: @posts %>

app/views/posts/new.html.erb
<%= render '/layouts/errors', error: @post %>
<%= render '/layouts/title', title: "New Post" %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render '/layouts/title', title: @user.username %>

<div class="well">
  <h3>Basic Information</h3>
  <span><h4>Username:</h4><%= @user.username %></span>
  <span><h4>Email:</h4><%= @user.email %></span>
</div>

<ul class='nav nav-tabs'>
  <li class="<%= 'active' if params[:tab] == nil %>">
    <%= link_to "Posts (#{current_user.posts.size})", user_path(current_user.id) %>
  </li>
  <li class="<%='active' if params[:tab] == 'comments' %>">
    <%= link_to "Comments (#{current_user.comments.size})", user_path(current_user.id, tab: 'comments') %>
  </li>
</ul>
<br>

<% if params[:tab] == nil %>
  <%= render '/posts/posts', posts: @user.posts %>
<% elsif params[:tab] == "comments" %>
  <%= render '/posts/comments', post: @user %>
<% end %>

app/views/votes/create.js.erb
$('#star_<%=@vote.voteable_id%>').replaceWith('<%=  j render "posts/stars", voted_object: @vote.voteable %>');

app/views/welcome/index.html.erb
<%= render '/layouts/errors', error: @user %>
<div class="logbox">
  <div id="centeredbox">
    <div id="centeredbox-inner">
      <% if params[:which_form] == nil %>
      <h1>Post It</h1>
      <p>post or comment anywhere, anytime</p>
        <%= link_to "Login", root_path(which_form: "login"), class: 'btn btn-lg btn-info'%>
        <a class='btn btn-lg btn-warning' href="?which_form=sign_up">Sign Up</a>
      <% elsif params[:which_form] == 'login' %>
        <%= render '/layouts/login' %>
      <% else %>
        <%= render '/layouts/sign_up' %>
      <% end %>
    </div>
  </div>
  <%= "#{User.find(session[:user_id]).username}" if session[:user_id] %>
</div>